services:
  mysql:
    container_name: 'guide-mysql'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=Supplier'
      - 'MYSQL_PASSWORD=12345678'
      - 'MYSQL_ROOT_PASSWORD=12345678'
      - 'MYSQL_USER=root'
    ports:
      - '3306:3306'

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
